baseURL: "https://lizzhang1369.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: PaperMod
paginate: 5
theme: PaperMod

baseURL: 'https://lizzhang1369.github.io/'
languageCode: en-us
title: The world in my mind
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

params:
    homeInfoParams:
        Title: Hi there wave
        Content: ...

